{% set name = "tornado_sqlalchemy_login" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c103e74086793215bfc627abc836548fce64981964190b6efac33e391a1a5eb6

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jinja2 >=2.10
    - requests >=2.22.0
    - sqlalchemy >=1.3.0
    - tornado >=6.0.3
    - ujson >=1.35

test:
  requires:
    - python {{ python_min }}
  imports:
    - tornado_sqlalchemy_login

about:
  home: http://github.com/timkpaine/tornado_sqlalchemy_login
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'SQLAlchemy helpers doing login/logout/register in Tornado'

  description: |
    SQLAlchemy helpers doing login/logout/register in Tornado
  dev_url: https://github.com/timkpaine/tornado_sqlalchemy_login

extra:
  recipe-maintainers:
    - timkpaine
